- NumPy 最重要的一个特点是其 N 维数组对象 ndarray
- 它是一系列同类型数据的集合，以 0 下标为开始进行集合中元素的索引。

##### 创建一个 ndarray

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

- order	创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
- ndmin	指定生成数组的最小维度
- dtype	数组元素的数据类型，可选

In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
# 最小维度的使用
a = np.array([1, 2, 3, 4, 5], ndmin = 3)
print(a)
print(a.shape)
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)
[1 2 3 4 5]
(5,)


In [11]:
# dtype的使用
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


ndarray 对象由计算机内存的连续一维部分组成，并结合索引模式，将每个元素映射到内存块中的一个位置。内存块以行顺序(C样式)或列顺序(FORTRAN或MatLab风格，即前述的F样式)来保存元素