- array函数创建数组
- arange创建
- np.zeros(shape, dtype=float, order='C'):创建一个全0数组，shape要以元组格式传入。
- np.ones(shape, dtype=None, order='C')：创建一个全1数组，shape要以元组格式传入。
- np.empty(shape, dtype=None, order='C')：创建一个拥有趋近0值的数组，shape要以元组格式传入。
- np.eye(N, M=None, k=0, dtype=float, order='C')：创建一个对角矩阵，N代表行，M代表列。其中有个参数k默认值为0，它代表偏移量，正1时向主对角线右上偏移1位，负1时向主对角线左下偏移1位。
- np.full(shape, fill_value, dtype=None, order='C')：创建一个以fill_value进行填充的数组，fill_value为想要填充的值
- np.linspace (起始值,终止值,元素总数)：创建一维等差数组。
- np.logspace(起始值,终止值,元素总数)：创建一维等比数组。

##### array函数创建
- array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

In [4]:
import numpy as np
ndarray1 = np.array([1, 2, 3, 4])
print(ndarray1)
ndarray2 = np.array(list('abcdef'))
print(ndarray2)
ndarray3 = np.array([[11, 22, 33, 44], [10, 20, 30, 40]])
print(ndarray3)

[1 2 3 4]
['a' 'b' 'c' 'd' 'e' 'f']
[[11 22 33 44]
 [10 20 30 40]]


##### zeros 和 zeros_like
数组元素默认值是0. 注意:zeros_linke函数只是根据传入的ndarray数组的shape来创建所有元素为0的数组，并不是拷贝源数组中的数据

In [6]:
ndarray4 = np.zeros(10)
print(ndarray4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
nda5 = np.zeros((3, 4))
print(nda5)
nda = np.arange(12).reshape((3,4))
print(nda)
nda6 = np.zeros_like(nda)
print(nda6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##### ones和ones_like创建数组
- 创建所有元素都为1的数组.ones_like用法同zeros_like用法

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones_like(nda6)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

##### empty 和 empty_like
用于清空数组，空数据中的值并不为0，而是未初始化的随机值

In [24]:
# np.set_printoptions(precision = 5)
nda7 = np.empty((3, 4))
print(nda7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### arange
- arange([start,] stop[, step,], dtype=None)
- arange函数是python内置函数range函数的数组版本.

In [26]:
nda8 = np.arange(10)
print(nda8)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
nda9 = np.arange(10, 20)
print(nda9)

[10 11 12 13 14 15 16 17 18 19]


In [29]:
nda10 = np.arange(2,20,2)
print(nda10)

[ 2  4  6  8 10 12 14 16 18]


##### eys创建对角矩阵数组
用于创建一个N*N的矩阵，对角线为1，其余为0.

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])