##### numpy.arange
创建数值范围并返回 ndarray 对象
- numpy.arange(start, stop, step, dtype)

In [1]:
import numpy as np

In [2]:
arr = np.arange(5, dtype='f2')
print(arr)

[0. 1. 2. 3. 4.]


##### numpy.linspace
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    - start	序列的起始值
    - stop	序列的终止值，如果endpoint为true，该值包含于数列中
    - num	要生成的等步长的样本数量，默认为50
    - endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
    - retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。
    - dtype	ndarray 的数据类型

In [3]:
a = np.linspace(1, 11, 20, endpoint=False, retstep=True)
print(a)

(array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5]), 0.5)


设置元素全部是1的等差数列

In [4]:
a = np.linspace(1, 1, 10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


将 endpoint 设为 false，不包含终止值：

In [5]:
a = np.linspace(10, 20, 5, endpoint = False )
print(a)

[10. 12. 14. 16. 18.]


##### numpy.logspace
numpy.logspace 函数用于创建一个于等比数列。格式如下：
- np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    - start	序列的起始值为：base ** start
    - stop	序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
    - num	要生成的等步长的样本数量，默认为50
    - endpoint	该值为 ture 时，数列中中包含stop值，反之不包含，默认是True。
    - base	对数 log 的底数。
    - dtype	ndarray 的数据类型
    
        - base 默认为10
        - endpoint 默认为True

In [14]:
a = np.logspace(0, 2, num = 10, base = 2)
print(a)

[1.         1.16652904 1.36079    1.58740105 1.85174942 2.16011948
 2.5198421  2.93946898 3.42897593 4.        ]


In [19]:
np.set_printoptions(precision=1)
b = np.logspace(0,9,10,base=3)
print(b)

[1.0e+00 3.0e+00 9.0e+00 2.7e+01 8.1e+01 2.4e+02 7.3e+02 2.2e+03 6.6e+03
 2.0e+04]
