- ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样
- ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组

- 冒号切片的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项

In [1]:
import numpy as np

In [9]:
a = np.arange(20)
s = slice(2, 7)
print(s)
print(a[s])

slice(2, 7, None)
[2 3 4 5 6]


In [11]:
b = np.arange(10)
c = b[2:7:2]
print(c)

[2 4 6]


##### 切片改变，原array被改变

In [15]:
# 冒号切片
a = np.arange(10)
b = a[2:]
print(b)
# 切片改变，原array被改变
b[3] = 111
print(a)
print(b)

[2 3 4 5 6 7 8 9]
[  0   1   2   3   4 111   6   7   8   9]
[  2   3   4 111   6   7   8   9]


##### 多维数组切片


In [17]:
# 多维数组
a = np.asarray([[1,2,3],[3,4,5],[4,5,6]])
print(a)
b = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(b)

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [20]:
# 多维数组切片
print(a[1:,1:])

[[4 5]
 [5 6]]


In [21]:
# 多维数组切片
print(a[1:,:1])

[[3]
 [4]]


##### 切片还可以包括省略号 …

In [22]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


##### :   等同于   ...

In [23]:
# 获取列          
arr1 = a[:,2]
print(arr1)
arr2 = a[...,2]
print(arr2)

[3 5 6]
[3 5 6]


In [24]:
# 获取行
arr3 = a[2,...]
print(arr3)
arr4 = a[2, :]
print(arr4)

[4 5 6]
[4 5 6]
