##### NumPy 比一般的 Python 序列提供更多的索引方式
- 除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引

In [1]:
import numpy as np

#### 整数数组索引
获取数组中(0,0)，(1,1)和(2,0)位置处的元素

In [2]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [3]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
print(x[rows, cols])

[[ 0  2]
 [ 9 11]]


##### 借助切片 : 或 … 与索引数组组合

In [4]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


#### 布尔索引
通过一个布尔数组来索引目标数组
- 布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组

In [5]:
# 获取大于 5 的元素
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]]) 
print(x)
print('大于5的mask:')
print(x>5)
print('大于5的元素：')
print(x[x>5])
a = x[x>5]
print(type(a), a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
大于5的mask:
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
大于5的元素：
[ 6  7  8  9 10 11]
<class 'numpy.ndarray'> (6,)


##### 使用了 ~（取补运算符）来过滤 NaN
np.isnan()

In [6]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a)

[nan  1.  2. nan  3.  4.  5.]


In [7]:
# np.isnan()
print(np.isnan(a))

[ True False False  True False False False]


In [8]:
# 使用~ 反转布尔值
print(~np.isnan(a))

[False  True  True False  True  True  True]


In [9]:
# 获取非nan值
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


##### 从数组中过滤掉非复数元素

In [10]:
a = np.array([1,  2+6j,  5,  3.5+5j])  
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


#### 花式索引
花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

花式索引跟切片不一样，它总是将数据复制到新数组中

###### 传入顺序索引数组

In [11]:
x = np.arange(32).reshape((8, 4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [12]:
# 获取对应行
print (x[[4,2,1,7]])

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


###### 传入倒序索引数组

In [13]:
# 获取对应行
x=np.arange(32).reshape((8,4))
print (x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


###### 传入多个索引数组（要使用np.ix_）

In [14]:
# 获取行列切片
x=np.arange(32).reshape((8,4))
print(x)
print (x[np.ix_([1,5],[0,3])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  7]
 [20 23]]


In [18]:
print(np.ix_([1, 5], [0, 3]))

(array([[1],
       [5]]), array([[0, 3]]))
