##### NumPy 算术函数包含简单的加减乘除: add()，subtract()，multiply() 和 divide()
数组必须具有相同的形状或符合数组广播规则


In [2]:
import numpy as np

a = np.arange(9,dtype = np.float_).reshape(3,3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [3]:
b = np.array([10,10,10])
print(b)

[10 10 10]


##### 相加

In [5]:
c = np.add(a,b)
print(c)

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


##### 相减

In [6]:
print(np.subtract(a,b))

[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


##### 相乘

In [7]:
print(np.multiply(a,b))

[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


##### 相除

In [8]:
print(np.divide(a,b))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


##### 倒数

In [9]:
a = np.array([0.25,  1.33,  1,  100])  
print(np.reciprocal(a))

[4.        0.7518797 1.        0.01     ]


##### 平方

In [13]:
a = np.array([10,100,1000])  
print(np.power(a,2))

[    100   10000 1000000]


##### 余数  numpy.mod() 
计算输入数组中相应元素的相除后的余数
- numpy.remainder() 也产生相同的结果

In [14]:
a = np.array([10,20,30])
b = np.array([3,5,7])
print(np.mod(a,b))

[1 0 2]


In [15]:
print(np.remainder(a,b))

[1 0 2]
