#### NumPy 提供了很多统计函数，用于从数组中查找最小元素，最大元素，百分位标准差和方差等

##### numpy.amin() 用于计算数组中的元素沿指定轴的最小值
numpy.amax() 用于计算数组中的元素沿指定轴的最大值

In [2]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [5]:
print(np.amin(a,1))

[3 3 2]


In [6]:
print(np.amax(a,0))

[8 7 9]


##### np.ptp()
计算数组中元素最大值与最小值的差（最大值 - 最小值）

In [4]:
print('最大值：{}\n最小值：{}'.format(np.amax(a),np.amin(a)))
print(np.ptp(a))

最大值：9
最小值：2
7


In [5]:
print(np.ptp(a,axis = 0))

[6 3 6]


In [6]:
print(np.ptp(a,axis = 1))

[4 5 7]


##### np.percentile(a, q, axis)
百分位数是统计中使用的度量，表示小于这个值的观察值的百分比
- a: 输入数组
- q: 要计算的百分位数，在 0 ~ 100 之间
- axis: 沿着它计算百分位数的轴

第 p 个百分位数是这样一个值，它使得至少有 p% 的数据项小于或等于这个值，且至少有 (100-p)% 的数据项大于或等于这个值。

percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)

In [7]:
a = np.array([[10,7,4],[3,2,1]])
print(a)
print(np.percentile(a,50))

[[10  7  4]
 [ 3  2  1]]
3.5


In [8]:
print(np.percentile(a,50,axis = 0))

[6.5 4.5 2.5]


In [9]:
print(np.percentile(a,50,axis = 1))

[7. 2.]


In [12]:
print(np.percentile(a,50,axis = 1,keepdims=True))

[[7.]
 [2.]]


##### np.median()
用于计算数组 a 中元素的中位数

In [14]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])  
print(a)

[[30 65 70]
 [80 95 10]
 [50 90 60]]


In [15]:
print('中位数')
print(np.median(a))

中位数
65.0


In [16]:
print(np.median(a,axis = 0))

[50. 90. 60.]


In [17]:
print(np.median(a,axis = 1))

[65. 80. 60.]


##### np.mean()
返回数组中元素的算术平均值

In [18]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [20]:
print(np.mean(a))
print(np.mean(a,axis = 0))
print(np.mean(a,axis = 1))

3.6666666666666665
[2.66666667 3.66666667 4.66666667]
[2. 4. 5.]


##### numpy.average()
函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值
- 不指定权重时相当于mean
- 如果 returned 参数设为 true，则返回权重的和  

数组[1,2,3,4]和相应的权重[4,3,2,1]
- 加权平均值 = (1\*4+2\*3+3\*2+4\*1)/(4+3+2+1)

In [22]:
a = np.array([1,2,3,4])
# 不指定权重时像相当于mean
print(np.average(a))
print(np.mean(a))

2.5
2.5


In [28]:
wts = np.array([4,3,2,5])
print(np.average(a,weights = wts))

2.5714285714285716


In [29]:
# 如果 returned 参数设为 true，则返回权重的和  
print(np.average(a,weights=wts,returned = True))

(2.5714285714285716, 14.0)


In [32]:
# 多维数组中可以指定计算的轴
a = np.arange(6).reshape(2,3)
print(a,a.shape)
wt = np.array([3,5])
print(wt,wt.shape)

[[0 1 2]
 [3 4 5]] (2, 3)
[3 5] (2,)


In [34]:
print(np.average(a,axis = 0,weights = wt))

[1.875 2.875 3.875]


In [35]:
print(np.average(a,axis = 0,weights = wt,returned=True))

(array([1.875, 2.875, 3.875]), array([8., 8., 8.]))


##### 标准差
- 标准差是一组数据平均值分散程度的一种度量
- 标准差是方差的算术平方根
- 公式：std = sqrt(mean((x - x.mean())**2))

方差：方差是衡量源数据和期望值相差的度量值
- 概率论中方差用来度量随机变量和其数学期望（即均值）之间的偏离程度
- 统计中的方差（样本方差）是每个样本值与全体样本值的平均数之差的平方值的平均数

如果数组是 [1，2，3，4]，则其平均值为 2.5。 因此，差的平方是 [2.25,0.25,0.25,2.25]，求出其平均值的的平方根，即 sqrt(5/4) ，结果为 1.1180339887498949。

In [37]:
print(np.std([1,2,3,4]))

1.118033988749895


##### 方差：mean((x - x.mean())** 2)
- 每个样本值与全体样本值的平均数之差的平方值的平均数
- 标准差是方差的平方根

In [38]:
print(np.var([1,2,3,4]))

1.25
