In [ ]:
# https://www.cnblogs.com/qflyue/p/8244331.html

#### 理解1

np.sum(a,axis = 1) 
- 那么这个axis=1实际上是说，只对第一轴进行相加操作
- 当axis=0时，即相加只对第一维度

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[1,2,3]])
print(np.sum(a,axis = 1))

[6 6]


In [3]:
print(np.sum(a,axis = 0))

[2 4 6]


#### 理解2

- axis = 0 代表对横轴操作，也就是第0轴；
- axis = 1 代表对纵轴操作，也就是第1轴；

In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
print(np.sum(a))

66


In [8]:
# 对行中的对应元素做操作,每行有多少元素就做几次操作
print(np.sum(a,axis = 0))

[12 15 18 21]


In [9]:
# 对列中的对应元素做操作，每列有几个元素就做几次操作
print(np.sum(a,axis = 1))

[ 6 22 38]


#### 为什么会有axis这个概念？
在numpy模块中，大多数处理的是矩阵或者多维数组，同时，对多维数组或者矩阵的操作有多种可能，为了帮助实现对数组或矩阵各种各样的功能，就有了axis

##### axis=0代表往跨行（down)，而axis=1代表跨列（across)，作为方法动作的副词

In [12]:
arr = np.arange(16).reshape(2,4,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [13]:
print(np.sum(arr))

120


In [14]:
print(np.sum(arr,axis = 0))

[[ 8 10]
 [12 14]
 [16 18]
 [20 22]]


In [15]:
print(np.sum(arr,axis = 1))

[[12 16]
 [44 48]]


In [16]:
print(np.sum(arr,axis = 2))

[[ 1  5  9 13]
 [17 21 25 29]]
