In [220]:
import pandas as pd

In [221]:
s = pd.Series([7, -3, 4, -2])
s

0    7
1   -3
2    4
3   -2
dtype: int64

In [222]:
print(s.values, s.index, end='\r\n')

[ 7 -3  4 -2] RangeIndex(start=0, stop=4, step=1)


In [223]:
dic = {'beijing':35000,'shanghai':71000,'guangzhou':16000,'shenzhen':5000}
s2 = pd.Series(dic)
s2

beijing      35000
shanghai     71000
guangzhou    16000
shenzhen      5000
dtype: int64

In [224]:
s3 = pd.Series(dic, index=['guangzhou','shenzhen'])
s3

guangzhou    16000
shenzhen      5000
dtype: int64

In [225]:
s3.name = 'test'

In [226]:
s3

guangzhou    16000
shenzhen      5000
Name: test, dtype: int64

In [227]:
s3.index.name = 'city'
s3

city
guangzhou    16000
shenzhen      5000
Name: test, dtype: int64

In [228]:
data = {'state':['beijing','beijing','beijing','shanghai','shanghai','shanghai'],
'year':[2000,2001,2002,2001,2002,2003],
'pop':[1.5, 1.7,3.6,2.4,2.9,3.2]}
f = pd.DataFrame(data)
f

state  year  pop
0   beijing  2000  1.5
1   beijing  2001  1.7
2   beijing  2002  3.6
3  shanghai  2001  2.4
4  shanghai  2002  2.9
5  shanghai  2003  3.2

In [229]:
f.pop

<bound method NDFrame.pop of       state  year  pop
0   beijing  2000  1.5
1   beijing  2001  1.7
2   beijing  2002  3.6
3  shanghai  2001  2.4
4  shanghai  2002  2.9
5  shanghai  2003  3.2>

In [230]:
f['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [231]:
f

state  year  pop
0   beijing  2000  1.5
1   beijing  2001  1.7
2   beijing  2002  3.6
3  shanghai  2001  2.4
4  shanghai  2002  2.9
5  shanghai  2003  3.2

In [232]:
f['append_col'] = 111

In [233]:
f

state  year  pop  append_col
0   beijing  2000  1.5         111
1   beijing  2001  1.7         111
2   beijing  2002  3.6         111
3  shanghai  2001  2.4         111
4  shanghai  2002  2.9         111
5  shanghai  2003  3.2         111

In [234]:
sub_f = f.loc[0]
sub_f

state         beijing
year             2000
pop               1.5
append_col        111
Name: 0, dtype: object

In [235]:
ff = f.append(sub_f)
ff

state  year  pop  append_col
0   beijing  2000  1.5         111
1   beijing  2001  1.7         111
2   beijing  2002  3.6         111
3  shanghai  2001  2.4         111
4  shanghai  2002  2.9         111
5  shanghai  2003  3.2         111
0   beijing  2000  1.5         111

In [236]:
# del ff['append_col']
ff

state  year  pop  append_col
0   beijing  2000  1.5         111
1   beijing  2001  1.7         111
2   beijing  2002  3.6         111
3  shanghai  2001  2.4         111
4  shanghai  2002  2.9         111
5  shanghai  2003  3.2         111
0   beijing  2000  1.5         111

In [237]:
ff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 0 to 0
Data columns (total 4 columns):
state         7 non-null object
year          7 non-null int64
pop           7 non-null float64
append_col    7 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 280.0+ bytes


In [238]:
import numpy as np

In [239]:
f = pd.DataFrame(np.arange(9).reshape((3,3)),index=list('acd'),columns=['beijing','shanghai','guangzhou'])
f

beijing  shanghai  guangzhou
a        0         1          2
c        3         4          5
d        6         7          8

In [240]:
f.reindex(list('abcd'))

beijing  shanghai  guangzhou
a      0.0       1.0        2.0
b      NaN       NaN        NaN
c      3.0       4.0        5.0
d      6.0       7.0        8.0

In [241]:
f.reindex(columns=['beijing','shanghai','xian','guangzhou'])


beijing  shanghai  xian  guangzhou
a        0         1   NaN          2
c        3         4   NaN          5
d        6         7   NaN          8

In [242]:
f.reindex(list('abcd'), axis='index')

beijing  shanghai  guangzhou
a      0.0       1.0        2.0
b      NaN       NaN        NaN
c      3.0       4.0        5.0
d      6.0       7.0        8.0

In [243]:
f

beijing  shanghai  guangzhou
a        0         1          2
c        3         4          5
d        6         7          8

In [244]:
f

beijing  shanghai  guangzhou
a        0         1          2
c        3         4          5
d        6         7          8

In [245]:
f.drop('a')

beijing  shanghai  guangzhou
c        3         4          5
d        6         7          8

In [246]:
df = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),index = ['one','two','three','four'])
df

b         d         e
one   -0.254726 -2.031515 -0.994691
two    0.422307  0.211277 -0.521490
three -0.448585  0.863224  1.718143
four   0.492705 -0.470263  0.332065

In [247]:
f = lambda x: x.max() - x.min()
df.apply(f)

b    0.941291
d    2.894739
e    2.712834
dtype: float64

In [248]:
df.sort_values(by='d',ascending=True)

b         d         e
one   -0.254726 -2.031515 -0.994691
four   0.492705 -0.470263  0.332065
two    0.422307  0.211277 -0.521490
three -0.448585  0.863224  1.718143

In [249]:
s = pd.Series([7,-5,7,4,2,0,4])
s.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [250]:
s.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [251]:
s.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [252]:
s.describe()

count    7.000000
mean     2.714286
std      4.231402
min     -5.000000
25%      1.000000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

In [253]:
s.quantile(0.25)

1.0

In [254]:
df.rank(axis=1)

b    d    e
one    3.0  1.0  2.0
two    3.0  2.0  1.0
three  1.0  2.0  3.0
four   3.0  1.0  2.0

In [255]:
df.mad()

b    0.404581
d    0.894070
e    0.891597
dtype: float64

In [256]:
df.mean()

b    0.052925
d   -0.356819
e    0.133507
dtype: float64

In [257]:
df.prod().prod()

0.001225989955374534

In [258]:
df.idxmax()

b     four
d    three
e    three
dtype: object

In [259]:
df

b         d         e
one   -0.254726 -2.031515 -0.994691
two    0.422307  0.211277 -0.521490
three -0.448585  0.863224  1.718143
four   0.492705 -0.470263  0.332065

In [260]:
df.idxmax(axis=1)

one      b
two      b
three    e
four     b
dtype: object

In [261]:
df.skew()

b   -0.123399
d   -0.938843
e    0.896735
dtype: float64

In [262]:
df.kurt()

b   -5.081469
d    0.762480
e   -0.042999
dtype: float64

In [263]:
df.diff(periods=2)

b         d         e
one         NaN       NaN       NaN
two         NaN       NaN       NaN
three -0.193859  2.894739  2.712834
four   0.070399 -0.681540  0.853555

In [264]:
df['b'].value_counts()

 0.422307    1
 0.492705    1
-0.254726    1
-0.448585    1
Name: b, dtype: int64

In [265]:
s = pd.Series(list('cadaabbcc'))
s.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [266]:
df = pd.read_csv('./data/csv_mindex.csv',index_col=['key1', 'key2'])
df

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [267]:
df = pd.DataFrame(np.arange(12).reshape((3, 4)),
                  index=['Ohio', 'Colorado', 'New York'],
                  columns=['one', 'two', 'three', 'four'])
print(df)
# 提取前四个并大写
transform = lambda x: x[:4].upper()
df.index = df.index.map(transform)
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11


one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [268]:
a = [0,-2,2]
np.sign(a)

array([ 0, -1,  1])

In [269]:
np.random.permutation(6)

array([0, 4, 1, 5, 2, 3])

In [270]:
sr = pd.Series(['aa','bb','cc'],index=['a','b','c'])
sr

a    aa
b    bb
c    cc
dtype: object

In [271]:
sr.str.upper()

a    AA
b    BB
c    CC
dtype: object

In [272]:
df = pd.read_csv('./data/csv_mindex.csv',index_col=['key1', 'key2'])
df

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [288]:
df.unstack(axis=1)

TypeError: unstack() got an unexpected keyword argument 'axis'

In [273]:
df.swaplevel('key1','key2')

value1  value2
key2 key1                
a    one        1       2
b    one        3       4
c    one        5       6
d    one        7       8
a    two        9      10
b    two       11      12
c    two       13      14
d    two       15      16

In [275]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2


In [276]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [277]:
pd.merge(df1, df2, how='outer', on='key')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [278]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                    'b': [np.nan, 2., np.nan, 6.],
                    'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],'b': [np.nan, 3., 4., 6., 8.]})

print(df1)
print(df2)

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14
     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0


In [279]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [280]:
df2.combine_first(df1)

a    b     c
0  5.0  NaN   2.0
1  4.0  3.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [281]:
df1 = pd.DataFrame({'A': [None, 0], 'B': [None, 4]})
df2 = pd.DataFrame({'A': [1, 1], 'B': [3, 3], "C":[None, 3]})
print(df1)
print(df2)
df1.combine_first(df2)

     A    B
0  NaN  NaN
1  0.0  4.0
   A  B    C
0  1  3  NaN
1  1  3  3.0


A    B    C
0  1.0  3.0  NaN
1  0.0  4.0  3.0

In [282]:
df1 = pd.DataFrame({'A': [0, 0], 'B': [4, 4]})
df2 = pd.DataFrame({'A': [1, 1], 'B': [3, 3]})
take_smaller = lambda s1, s2: s1 if s1.sum() < s2.sum() else s2
print(df1)
print(df2)

   A  B
0  0  4
1  0  4
   A  B
0  1  3
1  1  3


In [283]:
df1.combine(df2, take_smaller)

A  B
0  0  3
1  0  3

In [284]:
df1 = pd.DataFrame({'A': [0, 0], 'B': [None, 4]})
df2 = pd.DataFrame({'A': [1, 1], 'B': [3, 3], 'c':[1,4]})
df1.combine(df2, take_smaller, fill_value=-5)

A    B    c
0  0 -5.0 -5.0
1  0  4.0 -5.0

In [285]:
s = pd.Series(range(5))
s.where(s>3, 333)

0    333
1    333
2    333
3    333
4      4
dtype: int64

In [291]:
data = pd.DataFrame(np.arange(6).reshape((2,3)), index=pd.Index(['ohio', 'Colorado']),
                   columns = pd.Index(['one', 'tow','three'],name='number'))
data

number    one  tow  three
ohio        0    1      2
Colorado    3    4      5

In [294]:
result = data.stack()
result

          number
ohio      one       0
          tow       1
          three     2
Colorado  one       3
          tow       4
          three     5
dtype: int32

In [298]:
result.unstack(1)

number    one  tow  three
ohio        0    1      2
Colorado    3    4      5