In [1]:
import pandas as pd
import numpy as np

Pandas - pan(el)-da(ta)-s

面板(Panel)是3D容器的数据

3轴(axis)这个名称旨在给出描述涉及面板数据的操作的一些语义。它们是 
- items - axis 0，每个项目对应于内部包含的数据帧(DataFrame)
- major_axis - axis 1，它是每个数据帧(DataFrame)的索引(行)
- minor_axis - axis 2，它是每个数据帧(DataFrame)的列

### 创建面板 
pandas.Panel(data, items, major_axis, minor_axis, dtype, copy)
- data	数据采取各种形式，如：ndarray，series，map，lists，dict，constant和另一个数据帧(DataFrame)
- items	axis=0
- major_axis	axis=1
- minor_axis	axis=2
- dtype	每列的数据类型

#### 从3D ndarray创建

In [5]:
# rand(d0, d1, ..., dn)      Random values in a given shape.
data = np.random.rand(2,4,5)
print(data)
p = pd.Panel(data)
print(p)

[[[0.18252648 0.65660018 0.21828736 0.08289793 0.69008165]
  [0.38152691 0.37273923 0.1644577  0.46194451 0.69143726]
  [0.79216801 0.3171716  0.2543276  0.20750491 0.75175804]
  [0.11482468 0.70779947 0.6909232  0.38019337 0.79895831]]

 [[0.35243436 0.5082626  0.16515692 0.9538074  0.72333901]
  [0.3883761  0.28348955 0.64051945 0.82883639 0.71307326]
  [0.97637211 0.64972314 0.46054524 0.50102341 0.0211716 ]
  [0.5223784  0.29306731 0.87704366 0.4917814  0.84689154]]]
<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 5 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 4


C:\Users\Dell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


#### 从DataFrame对象的dict创建面板

In [9]:
data = {'item1':pd.DataFrame(np.random.randn(4,3)),
       'item2':pd.DataFrame(np.random.randn(4,2))}
p = pd.Panel(data)
print(p)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: item1 to item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2


C:\Users\Dell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


##### 创建一个空面板

In [10]:
p = pd.Panel()
print(p)

<class 'pandas.core.panel.Panel'>
Dimensions: 0 (items) x 0 (major_axis) x 0 (minor_axis)
Items axis: None
Major_axis axis: None
Minor_axis axis: None


C:\Users\Dell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


### 选择数据
要从面板中选择数据，可以使用以下方式 
- Items
- Major_axis
- Minor_axis

#### 使用items

In [13]:
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
        'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)
print(p['Item1'])
print(p['Item2'])

          0         1         2
0  0.995106  0.219615 -1.524843
1  0.001384 -1.310988 -0.144153
2 -1.094363  0.491156  1.999810
3 -0.345671 -0.904226  0.509023
          0         1   2
0 -1.802569 -2.371812 NaN
1  0.930160  0.873510 NaN
2  1.011744  1.472528 NaN
3 -1.703086 -0.161468 NaN


C:\Users\Dell\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


#### 使用major_axis
取行

In [16]:
print(p.major_xs(1))
print(p.major_axis)

      Item1    Item2
0  0.001384  0.93016
1 -1.310988  0.87351
2 -0.144153      NaN
RangeIndex(start=0, stop=4, step=1)


#### 使用minor_axis
取列

In [18]:
print(p.minor_axis)
print(p.minor_xs(0))

RangeIndex(start=0, stop=3, step=1)
      Item1     Item2
0  0.995106 -1.802569
1  0.001384  0.930160
2 -1.094363  1.011744
3 -0.345671 -1.703086
