In [85]:
import pandas as pd
from pandas import Series,DataFrame

In [86]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [87]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [88]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [89]:
obj.name = 'test'
obj.index.name= 'haha'
obj

haha
0    4
1    7
2   -5
3    3
Name: test, dtype: int64

In [90]:
obj.index = ['aa','bb','dd','cc']
obj

aa    4
bb    7
dd   -5
cc    3
Name: test, dtype: int64

In [91]:
data = {'state':['a','b','c','d','d'],
       'year':[2011,2002,2001,2011,2003],
       'pop':[1.5,1.7,6.3,2.9,2.4]}
frame = DataFrame(data)
print(frame)

  state  year  pop
0     a  2011  1.5
1     b  2002  1.7
2     c  2001  6.3
3     d  2011  2.9
4     d  2003  2.4


In [92]:
a = pd.Series([1,2,3],index=['a','b','c'])
a

a    1
b    2
c    3
dtype: int64

In [93]:
df = pd.DataFrame(data,columns=['year','state','pop'])
df

year state  pop
0  2011     a  1.5
1  2002     b  1.7
2  2001     c  6.3
3  2011     d  2.9
4  2003     d  2.4

In [94]:
sdata = {'ohio':35000,'texas':7100,'oregon':16000,'utah':5000}
states={'california','texas','haha','hello','wuwu'}
obj = pd.Series(sdata,index=states)
obj

texas         7100.0
haha             NaN
hello            NaN
california       NaN
wuwu             NaN
dtype: float64

In [95]:
sdata = [35000,7100,16000,5000]
states={'california','ohio','oregon','texas'}
obj = pd.Series(sdata,index=states)
obj

california    35000
oregon         7100
texas         16000
ohio           5000
dtype: int64

In [96]:
pop = {'a':{'A':1,'B':2},
      'b':{'C':3,'D':5}}
df = pd.DataFrame(pop)
print(df)
print(df.T)

     a    b
A  1.0  NaN
B  2.0  NaN
C  NaN  3.0
D  NaN  5.0
     A    B    C    D
a  1.0  2.0  NaN  NaN
b  NaN  NaN  3.0  5.0


In [97]:
df.index.name = 'aaa'
df.columns.name = 'AAA'
print(df)

AAA    a    b
aaa          
A    1.0  NaN
B    2.0  NaN
C    NaN  3.0
D    NaN  5.0


In [98]:
df.values

array([[ 1., nan],
       [ 2., nan],
       [nan,  3.],
       [nan,  5.]])

In [99]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [100]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [101]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [102]:
obj3 = pd.Series(['blue','yellow','red'],index=[0,2,3])
print(obj3)
print(obj3.reindex(range(6),method='ffill'))

0      blue
2    yellow
3       red
dtype: object
0      blue
1      blue
2    yellow
3       red
4       red
5       red
dtype: object


In [103]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','d','c'],
                     columns=['ohio','texas','california'])
frame

ohio  texas  california
a     0      1           2
d     3      4           5
c     6      7           8

In [104]:
frame.reindex(['a','b','c','d'])

ohio  texas  california
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   6.0    7.0         8.0
d   3.0    4.0         5.0

In [105]:
# 使用columns重新索引列
states = ['texas','california','bala']
frame.reindex(columns = states)

texas  california  bala
a      1           2   NaN
d      4           5   NaN
c      7           8   NaN

In [106]:
frame

ohio  texas  california
a     0      1           2
d     3      4           5
c     6      7           8

In [107]:
frame.reindex(index=['a','b','c','d'],columns=states).ffill()

texas  california  bala
a    1.0         2.0   NaN
b    1.0         2.0   NaN
c    7.0         8.0   NaN
d    4.0         5.0   NaN

In [108]:
frame.ix[['a','b','c','d'],states]

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


texas  california  bala
a    1.0         2.0   NaN
b    NaN         NaN   NaN
c    7.0         8.0   NaN
d    4.0         5.0   NaN

In [109]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
new_obj = obj.drop('c')  
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [110]:
# 索引选取和过滤
obj = pd.Series(np.arange(4.),index = ['a','b','c','d'])
print(obj['b'])
# 必须嵌套两层
print(obj[[1]])
print('------')
print(obj[1:3])
print(obj[['b','a']])
print(obj[[1,3]])
print(obj[obj<2])

1.0
b    1.0
dtype: float64
------
b    1.0
c    2.0
dtype: float64
b    1.0
a    0.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64


In [111]:
print(obj['b':'d'])

b    1.0
c    2.0
d    3.0
dtype: float64


In [112]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['ohio','colorado','utah','new york'],
                   columns=['one','two','three','four'])

data

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [113]:
data[:2]

one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7

In [114]:
data[['three','one']]

three  one
ohio          2    0
colorado      6    4
utah         10    8
new york     14   12

In [115]:
data[data['three']>5]

one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [116]:
data[data['three']>5] = 0

In [117]:
data

one  two  three  four
ohio        0    1      2     3
colorado    0    0      0     0
utah        0    0      0     0
new york    0    0      0     0

In [118]:
data.ix['ohio']

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one      0
two      1
three    2
four     3
Name: ohio, dtype: int32

In [119]:
?data.iloc

In [120]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['ohio','colorado','utah','new york'],
                   columns=['one','two','three','four'])
data.ix[2,3]

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


11

In [121]:
data.ix[2]

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one       8
two       9
three    10
four     11
Name: utah, dtype: int32

In [122]:
data.ix['colorado', ['tow', 'three']]

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\Dell\Anaconda3\lib\site-packages\pandas\core\indexing.py:1027: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return getattr(section, self.name)[new_key]


tow      NaN
three    6.0
Name: colorado, dtype: float64

In [123]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index = ['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])
print(s1,s2,sep='\n')

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [124]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [125]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))
print(df1,df2,sep='\n'+'_'*23+'\n')

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
_______________________
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19


In [126]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [127]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [128]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [129]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [130]:
arr = np.arange(12).reshape((3,4))
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [131]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),
                     index=['utah','ohil','texas','oregon'])
frame

b   d   e
utah    0   1   2
ohil    3   4   5
texas   6   7   8
oregon  9  10  11

In [132]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: utah, dtype: int32

In [133]:
frame - series

b  d  e
utah    0  0  0
ohil    3  3  3
texas   6  6  6
oregon  9  9  9

In [134]:
series2 = pd.Series(range(3), index=list('bef'))

In [135]:
frame + series2

b   d     e   f
utah    0.0 NaN   3.0 NaN
ohil    3.0 NaN   6.0 NaN
texas   6.0 NaN   9.0 NaN
oregon  9.0 NaN  12.0 NaN

In [136]:
# numpy 的ufuncs(元素级数组方法)也可以用于操作pandas
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), 
                    index=['aa','cc','bb','dd'])
frame

b         d         e
aa -1.442196 -0.108558  0.340864
cc  0.784413 -2.367730  0.288268
bb  1.388467  1.631523  0.962313
dd -1.131810 -0.695095  1.554221

In [137]:
np.abs(frame)

b         d         e
aa  1.442196  0.108558  0.340864
cc  0.784413  2.367730  0.288268
bb  1.388467  1.631523  0.962313
dd  1.131810  0.695095  1.554221

In [138]:
# 将函数应用到有各列或行组成的一维数组上，DataFrame的apply方法可实现：
fun = lambda x: x.max() - x.min()
frame.apply(fun)

b    2.830663
d    3.999253
e    1.265953
dtype: float64

In [139]:
frame.apply(fun, axis=1)

aa    1.783059
cc    3.152143
bb    0.669210
dd    2.686031
dtype: float64

In [140]:
frame.min()

b   -1.442196
d   -2.367730
e    0.288268
dtype: float64

In [141]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.442196 -2.367730  0.288268
max  1.388467  1.631523  1.554221

In [142]:
# fm = lambda x:format(x, '.2f')
fm = lambda x:'%.2f' %x
frame.applymap(fm)

b      d     e
aa  -1.44  -0.11  0.34
cc   0.78  -2.37  0.29
bb   1.39   1.63  0.96
dd  -1.13  -0.70  1.55

In [143]:
frame['e'].map(fm)

aa    0.34
cc    0.29
bb    0.96
dd    1.55
Name: e, dtype: object

In [144]:
obj = pd.Series(range(4), index=list('dabc'))
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [145]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index=['three', 'one'],
                     columns=list('dabc'))
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [146]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [147]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [148]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [149]:
obj = pd.Series([4,np.nan, 7, -3,np.nan, 2])
obj.sort_values()

3   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
4    NaN
dtype: float64

In [150]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [151]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [152]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [153]:
# obj.rank(method='first')
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [154]:
obj.rank(method='min')

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [155]:
obj.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [156]:
df = pd.DataFrame(data={'Animal': ['cat', 'penguin', 'dog', 'spider', 'snake'],
                        'Number_legs': [4, 2, 4, 8, np.nan]})
df

Animal  Number_legs
0      cat          4.0
1  penguin          2.0
2      dog          4.0
3   spider          8.0
4    snake          NaN

In [157]:
df['default_rank_average'] = df['Number_legs'].rank(method='average')
df['max_rank'] = df['Number_legs'].rank(method='max')
df['min_rank'] = df['Number_legs'].rank(method='min')
df['first_rank'] = df['Number_legs'].rank(method='first')
df['NA_botton'] = df['Number_legs'].rank(na_option='bottom')
df['pct_rank']  = df['Number_legs'].rank(pct=True)
df

Animal  Number_legs  default_rank_average  max_rank  min_rank  first_rank  \
0      cat          4.0                   2.5       3.0       2.0         2.0   
1  penguin          2.0                   1.0       1.0       1.0         1.0   
2      dog          4.0                   2.5       3.0       2.0         3.0   
3   spider          8.0                   4.0       4.0       4.0         4.0   
4    snake          NaN                   NaN       NaN       NaN         NaN   

   NA_botton  pct_rank  
0        2.5     0.625  
1        1.0     0.250  
2        2.5     0.625  
3        4.0     1.000  
4        5.0       NaN

In [158]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [159]:
obj.index.is_unique

False

In [160]:
obj['c']

4

In [161]:
obj['a']

a    0
a    1
dtype: int64

### 相关系数和协方差

In [163]:
import pandas_datareader.data as web

In [166]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()}) 
volume = pd.DataFrame({ticker: data['Volume']
                       for ticker, data in all_data.items()})

In [168]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-07-26  0.003478  0.006450  0.008203  0.104485
2019-07-29  0.009339 -0.003171 -0.002193 -0.008797
2019-07-30 -0.004292 -0.007357 -0.004822 -0.011514
2019-07-31  0.020404 -0.010216 -0.029070 -0.006905
2019-08-01  0.019048  0.028197  0.030968  0.012287

In [172]:
returns['MSFT'].corr(returns['IBM'])

0.4871151724138584

In [176]:
returns['MSFT'].cov(returns['IBM'])

8.656842905371599e-05

In [177]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.379356  0.452113  0.457141
IBM   0.379356  1.000000  0.487115  0.400139
MSFT  0.452113  0.487115  1.000000  0.534055
GOOG  0.457141  0.400139  0.534055  1.000000

In [178]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000265  0.000076  0.000106  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000106  0.000087  0.000208  0.000120
GOOG  0.000116  0.000077  0.000120  0.000242

In [179]:
returns.corrwith(returns.IBM)

AAPL    0.379356
IBM     1.000000
MSFT    0.487115
GOOG    0.400139
dtype: float64

In [182]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [190]:
aa = obj.unique()
aa

array(['c', 'a', 'd', 'b'], dtype=object)

In [189]:
aa.sort()
aa

array(['a', 'b', 'c', 'd'], dtype=object)

In [191]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [192]:
obj.isin(['b','c'])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [193]:
 data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                      'Qu2': [2, 3, 1, 2, 3],
                      'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [194]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [195]:
help(data.apply)

Help on method apply in module pandas.core.frame:

apply(func, axis=0, broadcast=None, raw=False, reduce=None, result_type=None, args=(), **kwds) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.
    
    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.
    
    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:
    
        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.
    broadcast : bool, optional
        Only relevant for aggregation functions:
    
       

In [198]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [199]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [200]:
to_match.isna()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object