#### NumPy 提供了很多统计函数，用于从数组中查找最小元素，最大元素，百分位标准差和方差等

##### numpy.amin() 用于计算数组中的元素沿指定轴的最小值
numpy.amax() 用于计算数组中的元素沿指定轴的最大值

In [2]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [5]:
print(np.amin(a,1))

[3 3 2]


In [6]:
print(np.amax(a,0))

[8 7 9]


##### np.ptp()
计算数组中元素最大值与最小值的差（最大值 - 最小值）

In [4]:
print('最大值：{}\n最小值：{}'.format(np.amax(a),np.amin(a)))
print(np.ptp(a))

最大值：9
最小值：2
7


In [5]:
print(np.ptp(a,axis = 0))

[6 3 6]


In [6]:
print(np.ptp(a,axis = 1))

[4 5 7]
